Add Lands protection
Wolfieheart/ArmorStandEditor pull request #116
Opened 2022-08-27 19:04 UTC by PlanetTeamSpeakk

#### Description:

Add protection against use in Lands claims
----
### [CORE] Changes
*Changes to the core of the plugin - Performance Fixes, Bug Fixes, New Features, New Permission Nodes, New Config Options etc.* 

Generalises the protection system so every protection does not have to be handled separately and adds protection for Lands claims.

----
### [CI] Changes
*Changes relating to the Continuous Integration of other Plugin APIs, Github Workflows, Issue Templates etc.*

Added Lands API as a dependency

----
### [DOC] Changes
*Changes relating to plugin Documentation - See the Wiki for more info*

None

----
### [MISC] Changes
*Changes that does not fit in the above list*

None

____
- [ x] I have tested this pull request for defects on a server.

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the ArmorStandEditor Project Owners have the copyright to use and modify my contribution under the ArmorStandEditor [License](https://github.com/Wolfieheart/ArmorStandEditor/blob/master/LICENSE.md) for perpetuity.

2022-08-27 19:06 UTC, Wolfieheart commented
Hey there, change that you could rebase this off the dev branch for me real fast and we can add this to the 1.19.2-37 branch ? If not no worries :)

2022-08-27 22:58 UTC, PlanetTeamSpeakk commented
I only forked the master branch, so I don't think I can.
Even if I can, I wouldn't know how, tbh.

2022-08-28 09:16 UTC, Wolfieheart commented
> I only forked the master branch, so I don't think I can. Even if I can, I wouldn't know how, tbh.

No worries :) Will have a look at this in a bit and merge it in then upfit to Dev myself :)

2022-08-28 09:19 UTC, Wolfieheart commented
Looks very nice - Adding a few tiny review remark, and then we can merge this in

2022-08-28 09:21 UTC, Wolfieheart commented on pom.xml
> +        <!-- Lands -->
Related to this can you bump the version to 1.19.2-37 please :)

2022-08-28 09:21 UTC, Wolfieheart commented on src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java
> +        return protections.stream().allMatch(protection -> protection.checkPermission(block, player));
Comments here to explain to people what this actually does ?

2022-08-28 09:23 UTC, Wolfieheart requested changes
Small remarks but nothing major just version bumping and commenting ;)

2022-08-28 09:23 UTC, Wolfieheart commented on src/main/resources/plugin.yml
> +softdepend: [Towny, WorldGuard, GriefPrevention, PlotSquared, Lands]
Also here bump to version 1.19.2-37 :)

2022-08-28 09:23 UTC, Wolfieheart commented on src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditorManager.java
> +        return protections.stream().allMatch(protection -> protection.checkPermission(block, player));
Comments here to explain to people what this actually does ?

2022-08-28 09:23 UTC, Wolfieheart commented on pom.xml
> +        <!-- Lands -->
Related to this can you bump the version to 1.19.2-37 please :)

2022-08-28 09:23 UTC, Wolfieheart commented on src/main/resources/plugin.yml
>  authors: [Wolfstorm, Marfjeh, miknes123, rypofalem, sekwah41, Sikatsu1997, Cool_boy, sumdream, Amaury Carrade, nicuch, kotarobo, prettydude, Jumpy91, Niasio, Patbox, Puremin0rez, Prof-Bloodstone]
Also add yourself in here to Authors list :)

2022-08-28 21:25 UTC, PlanetTeamSpeakk commented
All requested changes have been addressed. 👌

2022-08-29 11:56 UTC, Wolfieheart requested changes
I missed one thing when I reviewed it last. Sorry about this.

2022-08-29 11:56 UTC, Wolfieheart commented on src/main/java/io/github/rypofalem/armorstandeditor/protections/LandsProtection.java
> +        if (!landsEnabled) return true;
Add Bypass permission here, check the other protections to see how best do that. I missed this last time. My bad!

2022-08-29 11:56 UTC, Wolfieheart commented on src/main/java/io/github/rypofalem/armorstandeditor/protections/LandsProtection.java
> +        if (!landsEnabled) return true;
Also comments here might be ideal

2022-08-29 16:23 UTC, Wolfieheart approved these changes
Looks Good to me! Will wait for the flow to run and do a release for this :)

2022-08-29 16:27 UTC, merged