Add a bypass permission for towny protections
Wolfieheart/ArmorStandEditor pull request #76
Opened 2022-05-29 03:36 UTC by partydev

2022-05-29 14:47 UTC, Wolfieheart requested changes
Something that might need to be checked before I merge this in. I appreciate the contribution however, just something to be sure of before we go further.

2022-05-29 14:47 UTC, Wolfieheart commented on src/main/java/io/github/rypofalem/armorstandeditor/PlayerEditor.java
> +			if (TownyAPI.getInstance().isWilderness(getPlayer().getLocation()) && !getPlayer().hasPermission("asedit.bypass")) return;
Could it be possible that this already fixed in Development? 

See this for more info: https://github.com/Wolfieheart/ArmorStandEditor/blob/dev/1.18.2-35/src/main/java/io/github/rypofalem/armorstandeditor/protections/TownyProtection.java

2022-05-29 23:11 UTC, partydev commented
Understood, I did not notice that your dev branch addressed this. It was an issue that I noticed and fixed for my server and I wanted to pay it forward. Will close this and will check that branch in case I come up with any more ideas.

2022-05-29 23:11 UTC, closed without merging

2022-05-30 06:19 UTC, Wolfieheart commented
No worries. Thank you for contributing in any case and please do so in the
future if you think there are ideas in Dev that could be fixed in the long
run.

On Mon, 30 May 2022, 01:11 partymc, ***@***.***> wrote:

> Closed #76 <https://github.com/Wolfieheart/ArmorStandEditor/pull/76>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Wolfieheart/ArmorStandEditor/pull/76#event-6698869482>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEOFXLYIPQLSV6PJNCWESS3VMP2TVANCNFSM5XHQUJMA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>